---
title: "CoMarker | The Manual"
author: "Eléonore Schneegans^1^, Samuel Boulger^1^, Vicky Chau^1^, Nurun Fancy^1^, Johanna Jackson^1^, Paul M. Matthews^1^"
date: "`r format(Sys.time(), '%d %B %Y')`"
site: bookdown::bookdown_site
---

# Preface {.unnumbered}

This manual introduces a standardised, reproducible image analysis pipeline, CoMarker, which was built to vastly decrease the time taken to assess the colocalisation of tissue markers, whilst eliminating subjectivity and human bias. Our script takes a cell-based approach, utilising nuclei markers to count cells which are positive for any given marker(s) and analyse the colocalisation of said markers, both respective and irrespective of a defined region of interest. We have, however, developed functions which allow users without a nuclei marker to revert to area coverage as the method of analysis.

The pipeline is written in ImageJ Macro language (IJM) and R, but doesn't require previous knowledge of either programming language, making it user friendly. The purpose of this code is to save time, money and resources by automating the analysis of markers, whilst eliminating human bias, hence the script is capable of producing a report containing a range of box plots with annotated statistical significance from an input of raw images in a short period of time. CoMarker can either be ran manually using Fiji ImageJ and R Studio, or through the command line.

## The Purpose of CoMarker {.unnumbered}

CoMarker was designed to imitate manual counts by taking an independent cell-based approach to marker analysis. Existing standalone marker colocalisation analysis packages use a pixel-based approach to assess the area covered by any marker - therefore, in previous methods, colocalisation is described as the number of pixels covered by two or more markers.

We allow the use of this pixel based-approach for users without a nuclei marker, however it is recommended that a nuclei marker is used in order to make the most out of the pipeline. When using the cell-based approach, colocalisation is described as any cell containing both the defined reference marker and another included marker. Consequently, the produced results are a better representation of the expression of cellular markers when the required output is the identification of cells positive for markers.

CoMarker was designed for the analysis of images produced by imaging mass cytometry (IMC)- an immunohistochemistry technology that provides an integrative spatial tissue analysis. Nonetheless, CoMarker has the capacity to analyse images produced by any histochemistry method as long as the images for each marker are separated and not compiled together.

## Acknowledgements {.unnumbered}

CoMarker was developed by Eléonore Schneegans^1^, Samuel Boulger^1^ and Vicky Chau^1^ as part of the UK DRI [Multi-'omics Atlas Project](https://map-ad.org), directed by Johanna Jackson^1^.

^1^ UK Dementia Research Institute and Deparatment of Brain Sciences, Imperial College London, London, UK.

[Find the CoMarker Github page here.](https://github.com/MAP-AD/CoMarker)

[Find a YouTube video step-by-step instructions here.](https://www.youtube.com/watch?v=dDbgb5QRrnc)
